#+title: Lista de exercícios 3 - shell
#+author: Isabely Gonçalves Mariano 

* 1 - Com suas palavras, explique o que é um shell

ele que fornece acesso às ferramentas do sistema operacional. Faz a ligação entre o usuário e o sistema.



* 2 - Quero executar esta sequência de comandos: ~cat xx.txt, ls, sort~ e guardar num arquivo ~.txt~. Cite ao menos uma forma de fazer isso, de maneira que o arquivo final tenha o conteúdo do ~ls~ e do ~cat~, não importando a ordem dos comandos.

Cat xxt.txt> arquivo.txt; ls> arquivo.txt;sort> arquivo.txt;




* 3 - Qual a utilidade de usar a técnica de ~shebang~?

Para poder usar vários comandos de rotina em um comando só


* 4 - Abaixo, serão listadas várias ações. Execute uma por vez no terminal e escreva o comando que usou logo em seguida. 

| ação                                                                                                          | comando |
|---------------------------------------------------------------------------------------------------------------+---------|
| Verifique em qual diretório você está                                                                         |pdw      |
| Crie a estrutura de diretórios sugerida logo acima na ~home~ do usuário                                       |mkdir ccuenf ; mkdir exercicios |
| Crie um arquivo "numeros.txt" com o ~cat~, não importa a quantidade de números                                |cat > numeros.txt         |
| Duplique "numeros.txt" para "numeros1.txt" e "numeros2.txt"                                              |cp numeros.txt numeros1.txt   cp numeros.txt numero2.txt|
| Copie todos os arquivos com extensão ~.txt~ para a pasta "exercicios"                                         |cp ./*.txt/exercicios|
| Exiba os arquivos da pasta "exercicios" com seus detalhes (permissões, tamanho e etc) sem sair da pasta atual |ls exercicios -1         |
| Apague a pasta "ccuenf" e "exercicios"                                                                        |rm /exercicios/*   rmdir ccuenf exercicios |




* 5 - Liste todos os arquivos da pasta ~/bin~, salve em arquivo e orderne alfabeticamente. Quais foram os comandos utilizados? Não é obrigatório executar a sequência em apenas uma linha. (corrigida)

ls /bis | tac > text.txt



* 6 - Crie um arquivo ~.txt~ com o centeúdo da execução de ~man <comando>~ - onde "comando" é qualquer comando linux conhecido e que possua um manual - e inverta a ordem das linhas, procure pela palavra "the" e conte o número de ocorrências. Coloque aqui seu resultado e qual comando usou para pegar o manual.

man rm > aux.txt
tac aux.txt > arquivo.txt
grep the arquivo.txt


* 7 - Escolha um ou mais programas da lista e tente instalá-lo, execute-o e descreva o resultado.
| programas |
|-----------|
| sl        |
| cmatrix   | vários caracteres ficam passando pela tela 
| rig       |
| nyancat   | um gato passando deixando arco-íris

- Após terminar o exercício, remova o programa



* 8 - Qual o resultado das seguintes expressões?
- Já que as colunas da tabela são formadas por ~|~, não posso escrever o pipe dentro da tabela.
  Tem como escapar com o ~\vert~, porém ele só é renderizado no ~org-mode~ do ~emacs~ :/
- ~\vert~ == ~|~

| expressão                               | resultado |
|-------------------------------+---------|
| =false && echo foo \vert\vert echo bar= | bar          |
| =true && echo foo \vert\vert echo bar=  | foo          |
| =true \vert\vert echo foo && echo bar=  | bar          |
| =false \vert\vert echo foo && echo bar= | foo  bar     |